### PR TITLE
Add future CTFs

### PR DESCRIPTION
**Pull request by Ik0ri4n**
Suggest good CTF competitions of our German friends for our calendar.

### CODE REVIEW

**Comment by Ik0ri4n** [comment]
**TODOs before merge:**
- [ ] Generate calendar

**Comment by intrigus-lgtm** [comment]
While GlacierCTF is not from a german team, I would still also add it.

**Comment by Ik0ri4n** [comment]
> While GlacierCTF is not from a german team, I would still also add it.

I included that and saarCTF and LakeCTF Quals in the new commit. I'll announce that later today for review.

**Comment by intrigus-lgtm** [comment]
Thank you!

**Pull request merged**
